#!/bin/bash
micro_ver='micro-1.3.4-67'

str="https://github.com/zyedidia/micro/releases/download/nightly/${micro_ver}-linux64.tar.gz"

curl -o micro.tar.gz -L $str
tar -xzf micro.tar.gz
rm micro.tar.gz

if [ -f /usr/bin/micro ]
then
    rm -f /usr/bin/micro
fi
cp $micro_ver/micro /usr/bin
rm -rf $micro_ver

mkdir -p ~/.config/micro/syntax
mkdir -p ~/.config/micro/colorschemes 

git clone https://github.com/zyedidia/micro
cp -r micro/runtime/syntax/* ~/.config/micro/syntax
cp -r micro/runtime/colorschemes/ ~/.config/micro/colorschemes
rm -rf micro

cp ./settings.json ~/.config/micro/

echo "export EDIOR=micro" >> ~/.zshrc
