#!/usr/bin/bash
micro_ver='micro-1.3.3-dev.10'

curl -o micro.tar.gz -L https://github.com/zyedidia/micro/releases/download/nightly/micro-1.3.3-dev.10-linux64.tar.gz
tar -xzf micro.tar.gz
rm micro.tar.gz

cp $micro_ver/micro /usr/bin
rm -rf $micro_ver

mkdir -p ~/.config/micro/syntax
mkdir -p ~/.config/micro/colorschemes 

git clone git@github.com:mrsndmn/micro.git
cp micro/runtime/syntax/* ~/.config/micro/syntax
cp micro/runtime/colorschemes/ ~/.config/micro/colorschemes
rm -rf micro

cp ./settings.json ~/.config/micro/settings.json